services:
  nginx:
    depends_on:
      - daphne
    image: nginx
    ports:
      - '443:443'
    volumes:
      - './files/nginx/templates:/etc/nginx/templates'
      - './files/ssl:/etc/ssl/numbas'
      - numbas:/srv
    restart: always 
  redis:
    expose:
      - "6379"
    image: redis
    volumes:
      - redis:/data
    restart: always 
  postgres:
    env_file:
      - 'settings.env'
    environment:
      POSTGRES_DB: numbas_lti
      POSTGRES_USER: numbas_lti
    expose:
      - "5432"
    image: postgres:18
    restart: always 
  numbas-setup:
    env_file:
      - 'settings.env'
    image: numbas/numbas-lti-provider
    depends_on:
      - postgres
      - redis
    volumes:
      - numbas:/srv
      - ./files/numbas-lti-provider:/setup-files
    working_dir: /setup-files
  daphne:
    env_file:
      - 'settings.env'
    image: numbas/numbas-lti-provider
    command: /usr/local/bin/daphne numbasltiprovider.asgi:application --port 8700 --bind 0.0.0.0 -v 2
    depends_on:
      - postgres
      - redis
    expose:
      - "8700"
    restart: always 
    user: www-data
    volumes:
      - numbas:/srv
    working_dir: /opt/numbas-lti-provider
  huey:
    env_file:
      - 'settings.env'
    image: numbas/numbas-lti-provider
    command: /usr/local/bin/python /opt/numbas-lti-provider/manage.py run_huey
    depends_on:
      - postgres
      - redis
    restart: always 
    user: www-data
    volumes:
      - numbas:/srv
    working_dir: /opt/numbas-lti-provider/
volumes: 
  numbas:
  redis:
